In [5]:
%matplotlib inline

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="darkgrid")

In [8]:
df = pd.read_csv('./24-01-18/01_JAN.csv')

C:\Users\ppetrov\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (24,25,26,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
df.head()

,DATE,BATT_V_DC,BATT_CHR_A_DC,BATT_DCHR_A_DC,BATT_S_V_DC,BATT_S_CHR_A_DC,BATT_S_DCHR_A_DC,CP_V_OUT,CP_I_OUT,BATT_TEMP,...,ALRM_SML,ALRM_SML_S,ALRM_CP_MODULE,ALRM_CP_U_HIGH,ALRM_CP_U_LOW,ALRM_CP_I_HIGH,ALRM_CP_I_LOW,ALRM_CP_P_HIGH,ALRM_CP_P_LOW,Unnamed: 60
0,01-01-18/00:00,49.6V,0A,12A,49.9V,0A,0A,9.7V,44.9A,20C,...,-,-,-,-,-,-,-,-,-,NaN
1,01-01-18/00:01,49.6V,0A,11A,49.9V,0A,0A,9.6V,44.9A,20C,...,-,-,-,-,-,-,-,-,-,NaN
2,01-01-18/00:02,49.6V,0A,11A,49.9V,0A,0A,9.6V,45.0A,20C,...,-,-,-,-,-,-,-,-,-,NaN
3,01-01-18/00:03,49.6V,0A,11A,49.9V,0A,0A,9.6V,44.9A,20C,...,-,-,-,-,-,-,-,-,-,NaN
4,01-01-18/00:04,49.6V,0A,11A,49.9V,0A,0A,9.6V,44.9A,20C,...,-,-,-,-,-,-,-,-,-,NaN